version: '3.9'

services:
  api:
    build:
      context: ./backend
    container_name: smart-study-api
    env_file:
      - ./backend/.env.example
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:7
    container_name: smart-study-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: smart-study-redis
    restart: unless-stopped
    ports:
      - '6379:6379'

volumes:
  mongo_data:
